---
name: Python Checks for Pull Requests
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5
      - name: Check for Python files changes
        id: changed
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62  # v47
        with:
          files: |
            **/*.py
      - name: Black Lint
        if: steps.changed.outputs.any_changed == 'true'
        uses: psf/black@af0ba72a73598c76189d6dd1b21d8532255d5942  # 25.9.0
      - name: Setup python environment for flake8 check
        if: steps.changed.outputs.any_changed == 'true'
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c  # v6
        with:
          python-version: "3.13"
      - name: flake8 Lint
        if: steps.changed.outputs.any_changed == 'true'
        uses: py-actions/flake8@84ec6726560b6d5bd68f2a5bed83d62b52bb50ba  # v2.3.0
      - name: Run pytest
        if: steps.changed.outputs.any_changed == 'true'
        run: |
          python -m pip install -r jira-ci/requirements.txt
          pytest
