name: "Pull Request Assignee Manager"
description: "Automatically assigns PRs to users and sends Slack notifications."

inputs:
  event-type:
    description: "The type of the pull request event (e.g., opened, ready_for_review, unassigned)."
    required: true
  pr-number:
    description: "The number of the pull request."
    required: true
  removed-assignee:
    description: "The login of the assignee that was removed (if applicable)."
    required: false
    default: ""
  github-token:
    description: "The GitHub token for making API calls."
    required: true
  slack-webhook:
    description: "The Slack webhook URL for notifications."
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout the action's repo to get user map
      uses: actions/checkout@v4
      with:
        repository: konflux-ci/release-service-automations
        ref: development
        path: './.action-repo'
        token: ${{ inputs.github-token }}

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: ./.action-repo/pr-assigner
      shell: bash
      run: npm install --legacy-peer-deps

    - name: Run pr-assignee script
      working-directory: ./.action-repo/pr-assigner
      shell: bash
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
        EVENT_TYPE: ${{ inputs.event-type }}
        REMOVED_ASSIGNEE: ${{ inputs.removed-assignee }}
        GH_TOKEN: ${{ inputs.github-token }}
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
        USER_MAP_FILE_PATH: '../user-map.yaml'
      run: node assign_assignees.js
